// Mocks generated by Mockito 5.4.6 from annotations
// in gru_songs/test/sleep_timer_full_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:audio_session/audio_session.dart' as _i12;
import 'package:flutter/services.dart' as _i10;
import 'package:flutter/widgets.dart' as _i2;
import 'package:gru_songs/models/queue_item.dart' as _i6;
import 'package:gru_songs/models/shuffle_config.dart' as _i5;
import 'package:gru_songs/models/song.dart' as _i7;
import 'package:gru_songs/services/audio_player_manager.dart' as _i4;
import 'package:just_audio/just_audio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAudioPlayer_1 extends _i1.SmartFake implements _i3.AudioPlayer {
  _FakeAudioPlayer_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerEvent_2 extends _i1.SmartFake implements _i3.PlayerEvent {
  _FakePlayerEvent_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaybackEvent_3 extends _i1.SmartFake implements _i3.PlaybackEvent {
  _FakePlaybackEvent_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerState_5 extends _i1.SmartFake implements _i3.PlayerState {
  _FakePlayerState_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSequenceState_6 extends _i1.SmartFake implements _i3.SequenceState {
  _FakeSequenceState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioPlayerManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayerManager extends _i1.Mock
    implements _i4.AudioPlayerManager {
  MockAudioPlayerManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<bool> get shuffleNotifier => (super.noSuchMethod(
        Invocation.getter(#shuffleNotifier),
        returnValue: _FakeValueNotifier_0<bool>(
          this,
          Invocation.getter(#shuffleNotifier),
        ),
      ) as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<_i5.ShuffleState> get shuffleStateNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#shuffleStateNotifier),
        returnValue: _FakeValueNotifier_0<_i5.ShuffleState>(
          this,
          Invocation.getter(#shuffleStateNotifier),
        ),
      ) as _i2.ValueNotifier<_i5.ShuffleState>);

  @override
  _i2.ValueNotifier<List<_i6.QueueItem>> get queueNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#queueNotifier),
        returnValue: _FakeValueNotifier_0<List<_i6.QueueItem>>(
          this,
          Invocation.getter(#queueNotifier),
        ),
      ) as _i2.ValueNotifier<List<_i6.QueueItem>>);

  @override
  _i2.ValueNotifier<_i7.Song?> get currentSongNotifier => (super.noSuchMethod(
        Invocation.getter(#currentSongNotifier),
        returnValue: _FakeValueNotifier_0<_i7.Song?>(
          this,
          Invocation.getter(#currentSongNotifier),
        ),
      ) as _i2.ValueNotifier<_i7.Song?>);

  @override
  _i3.AudioPlayer get player => (super.noSuchMethod(
        Invocation.getter(#player),
        returnValue: _FakeAudioPlayer_1(
          this,
          Invocation.getter(#player),
        ),
      ) as _i3.AudioPlayer);

  @override
  void setUserData({
    List<String>? favorites,
    List<String>? suggestLess,
    List<String>? hidden,
    Map<String, List<String>>? mergedGroups,
    Map<String, String?>? mergedGroupPriorities,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setUserData,
          [],
          {
            #favorites: favorites,
            #suggestLess: suggestLess,
            #hidden: hidden,
            #mergedGroups: mergedGroups,
            #mergedGroupPriorities: mergedGroupPriorities,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> updateShuffleConfig(_i5.ShuffleConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShuffleConfig,
          [config],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateShuffleState(_i5.ShuffleState? newState) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShuffleState,
          [newState],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playSong(
    _i7.Song? song, {
    List<_i7.Song>? contextQueue,
    bool? startPlaying = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playSong,
          [song],
          {
            #contextQueue: contextQueue,
            #startPlaying: startPlaying,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.ShuffleState?> syncShuffleState() => (super.noSuchMethod(
        Invocation.method(
          #syncShuffleState,
          [],
        ),
        returnValue: _i8.Future<_i5.ShuffleState?>.value(),
      ) as _i8.Future<_i5.ShuffleState?>);

  @override
  void didChangeAppLifecycleState(_i9.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> init(
    List<_i7.Song>? songs, {
    bool? autoSelect = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [songs],
          {#autoSelect: autoSelect},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void refreshSongs(List<_i7.Song>? newSongs) => super.noSuchMethod(
        Invocation.method(
          #refreshSongs,
          [newSongs],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> shuffleAndPlay(
    List<_i7.Song>? songs, {
    bool? isRestricted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shuffleAndPlay,
          [songs],
          {#isRestricted: isRestricted},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> toggleShuffle() => (super.noSuchMethod(
        Invocation.method(
          #toggleShuffle,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> playNext(_i7.Song? song) => (super.noSuchMethod(
        Invocation.method(
          #playNext,
          [song],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> reorderQueue(
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderQueue,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromQueue(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeFromQueue,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void forceFlushCurrentStats() => super.noSuchMethod(
        Invocation.method(
          #forceFlushCurrentStats,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  bool handleStartBackGesture(_i10.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleStartBackGesture,
          [backEvent],
        ),
        returnValue: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i10.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #handleUpdateBackGestureProgress,
          [backEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCommitBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCancelBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> didPushRouteInformation(
          _i2.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeLocales(List<_i9.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i9.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #didChangeViewFocus,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i9.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i8.Future<_i9.AppExitResponse>.value(_i9.AppExitResponse.exit),
      ) as _i8.Future<_i9.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i3.AudioPlayer {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.PlayerEvent get playerEvent => (super.noSuchMethod(
        Invocation.getter(#playerEvent),
        returnValue: _FakePlayerEvent_2(
          this,
          Invocation.getter(#playerEvent),
        ),
      ) as _i3.PlayerEvent);

  @override
  _i8.Stream<_i3.PlayerEvent> get playerEventStream => (super.noSuchMethod(
        Invocation.getter(#playerEventStream),
        returnValue: _i8.Stream<_i3.PlayerEvent>.empty(),
      ) as _i8.Stream<_i3.PlayerEvent>);

  @override
  _i3.PlaybackEvent get playbackEvent => (super.noSuchMethod(
        Invocation.getter(#playbackEvent),
        returnValue: _FakePlaybackEvent_3(
          this,
          Invocation.getter(#playbackEvent),
        ),
      ) as _i3.PlaybackEvent);

  @override
  _i8.Stream<_i3.PlaybackEvent> get playbackEventStream => (super.noSuchMethod(
        Invocation.getter(#playbackEventStream),
        returnValue: _i8.Stream<_i3.PlaybackEvent>.empty(),
      ) as _i8.Stream<_i3.PlaybackEvent>);

  @override
  _i8.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i8.Stream<Duration?>.empty(),
      ) as _i8.Stream<Duration?>);

  @override
  _i3.ProcessingState get processingState => (super.noSuchMethod(
        Invocation.getter(#processingState),
        returnValue: _i3.ProcessingState.idle,
      ) as _i3.ProcessingState);

  @override
  _i8.Stream<_i3.ProcessingState> get processingStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#processingStateStream),
        returnValue: _i8.Stream<_i3.ProcessingState>.empty(),
      ) as _i8.Stream<_i3.ProcessingState>);

  @override
  bool get playing => (super.noSuchMethod(
        Invocation.getter(#playing),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<bool> get playingStream => (super.noSuchMethod(
        Invocation.getter(#playingStream),
        returnValue: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
      ) as double);

  @override
  _i8.Stream<double> get volumeStream => (super.noSuchMethod(
        Invocation.getter(#volumeStream),
        returnValue: _i8.Stream<double>.empty(),
      ) as _i8.Stream<double>);

  @override
  double get speed => (super.noSuchMethod(
        Invocation.getter(#speed),
        returnValue: 0.0,
      ) as double);

  @override
  _i8.Stream<double> get speedStream => (super.noSuchMethod(
        Invocation.getter(#speedStream),
        returnValue: _i8.Stream<double>.empty(),
      ) as _i8.Stream<double>);

  @override
  double get pitch => (super.noSuchMethod(
        Invocation.getter(#pitch),
        returnValue: 0.0,
      ) as double);

  @override
  _i8.Stream<double> get pitchStream => (super.noSuchMethod(
        Invocation.getter(#pitchStream),
        returnValue: _i8.Stream<double>.empty(),
      ) as _i8.Stream<double>);

  @override
  bool get skipSilenceEnabled => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<bool> get skipSilenceEnabledStream => (super.noSuchMethod(
        Invocation.getter(#skipSilenceEnabledStream),
        returnValue: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  Duration get bufferedPosition => (super.noSuchMethod(
        Invocation.getter(#bufferedPosition),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#bufferedPosition),
        ),
      ) as Duration);

  @override
  _i8.Stream<Duration> get bufferedPositionStream => (super.noSuchMethod(
        Invocation.getter(#bufferedPositionStream),
        returnValue: _i8.Stream<Duration>.empty(),
      ) as _i8.Stream<Duration>);

  @override
  _i8.Stream<_i3.IcyMetadata?> get icyMetadataStream => (super.noSuchMethod(
        Invocation.getter(#icyMetadataStream),
        returnValue: _i8.Stream<_i3.IcyMetadata?>.empty(),
      ) as _i8.Stream<_i3.IcyMetadata?>);

  @override
  _i3.PlayerState get playerState => (super.noSuchMethod(
        Invocation.getter(#playerState),
        returnValue: _FakePlayerState_5(
          this,
          Invocation.getter(#playerState),
        ),
      ) as _i3.PlayerState);

  @override
  _i8.Stream<_i3.PlayerState> get playerStateStream => (super.noSuchMethod(
        Invocation.getter(#playerStateStream),
        returnValue: _i8.Stream<_i3.PlayerState>.empty(),
      ) as _i8.Stream<_i3.PlayerState>);

  @override
  List<_i3.IndexedAudioSource> get sequence => (super.noSuchMethod(
        Invocation.getter(#sequence),
        returnValue: <_i3.IndexedAudioSource>[],
      ) as List<_i3.IndexedAudioSource>);

  @override
  _i8.Stream<List<_i3.IndexedAudioSource>> get sequenceStream =>
      (super.noSuchMethod(
        Invocation.getter(#sequenceStream),
        returnValue: _i8.Stream<List<_i3.IndexedAudioSource>>.empty(),
      ) as _i8.Stream<List<_i3.IndexedAudioSource>>);

  @override
  List<int> get shuffleIndices => (super.noSuchMethod(
        Invocation.getter(#shuffleIndices),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i8.Stream<List<int>> get shuffleIndicesStream => (super.noSuchMethod(
        Invocation.getter(#shuffleIndicesStream),
        returnValue: _i8.Stream<List<int>>.empty(),
      ) as _i8.Stream<List<int>>);

  @override
  _i8.Stream<int?> get currentIndexStream => (super.noSuchMethod(
        Invocation.getter(#currentIndexStream),
        returnValue: _i8.Stream<int?>.empty(),
      ) as _i8.Stream<int?>);

  @override
  _i3.SequenceState get sequenceState => (super.noSuchMethod(
        Invocation.getter(#sequenceState),
        returnValue: _FakeSequenceState_6(
          this,
          Invocation.getter(#sequenceState),
        ),
      ) as _i3.SequenceState);

  @override
  _i8.Stream<_i3.SequenceState> get sequenceStateStream => (super.noSuchMethod(
        Invocation.getter(#sequenceStateStream),
        returnValue: _i8.Stream<_i3.SequenceState>.empty(),
      ) as _i8.Stream<_i3.SequenceState>);

  @override
  bool get hasNext => (super.noSuchMethod(
        Invocation.getter(#hasNext),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPrevious => (super.noSuchMethod(
        Invocation.getter(#hasPrevious),
        returnValue: false,
      ) as bool);

  @override
  List<int> get effectiveIndices => (super.noSuchMethod(
        Invocation.getter(#effectiveIndices),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i3.LoopMode get loopMode => (super.noSuchMethod(
        Invocation.getter(#loopMode),
        returnValue: _i3.LoopMode.off,
      ) as _i3.LoopMode);

  @override
  _i8.Stream<_i3.LoopMode> get loopModeStream => (super.noSuchMethod(
        Invocation.getter(#loopModeStream),
        returnValue: _i8.Stream<_i3.LoopMode>.empty(),
      ) as _i8.Stream<_i3.LoopMode>);

  @override
  bool get shuffleModeEnabled => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabled),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<bool> get shuffleModeEnabledStream => (super.noSuchMethod(
        Invocation.getter(#shuffleModeEnabledStream),
        returnValue: _i8.Stream<bool>.empty(),
      ) as _i8.Stream<bool>);

  @override
  _i8.Stream<int?> get androidAudioSessionIdStream => (super.noSuchMethod(
        Invocation.getter(#androidAudioSessionIdStream),
        returnValue: _i8.Stream<int?>.empty(),
      ) as _i8.Stream<int?>);

  @override
  _i8.Stream<_i3.PlayerException> get errorStream => (super.noSuchMethod(
        Invocation.getter(#errorStream),
        returnValue: _i8.Stream<_i3.PlayerException>.empty(),
      ) as _i8.Stream<_i3.PlayerException>);

  @override
  _i8.Stream<_i3.PositionDiscontinuity> get positionDiscontinuityStream =>
      (super.noSuchMethod(
        Invocation.getter(#positionDiscontinuityStream),
        returnValue: _i8.Stream<_i3.PositionDiscontinuity>.empty(),
      ) as _i8.Stream<_i3.PositionDiscontinuity>);

  @override
  bool get automaticallyWaitsToMinimizeStalling => (super.noSuchMethod(
        Invocation.getter(#automaticallyWaitsToMinimizeStalling),
        returnValue: false,
      ) as bool);

  @override
  bool get canUseNetworkResourcesForLiveStreamingWhilePaused =>
      (super.noSuchMethod(
        Invocation.getter(#canUseNetworkResourcesForLiveStreamingWhilePaused),
        returnValue: false,
      ) as bool);

  @override
  double get preferredPeakBitRate => (super.noSuchMethod(
        Invocation.getter(#preferredPeakBitRate),
        returnValue: 0.0,
      ) as double);

  @override
  bool get allowsExternalPlayback => (super.noSuchMethod(
        Invocation.getter(#allowsExternalPlayback),
        returnValue: false,
      ) as bool);

  @override
  String get webSinkId => (super.noSuchMethod(
        Invocation.getter(#webSinkId),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#webSinkId),
        ),
      ) as String);

  @override
  Duration get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#position),
        ),
      ) as Duration);

  @override
  _i8.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i8.Stream<Duration>.empty(),
      ) as _i8.Stream<Duration>);

  @override
  List<_i3.AudioSource> get audioSources => (super.noSuchMethod(
        Invocation.getter(#audioSources),
        returnValue: <_i3.AudioSource>[],
      ) as List<_i3.AudioSource>);

  @override
  _i8.Stream<Duration> createPositionStream({
    int? steps = 800,
    Duration? minPeriod = const Duration(milliseconds: 200),
    Duration? maxPeriod = const Duration(milliseconds: 200),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPositionStream,
          [],
          {
            #steps: steps,
            #minPeriod: minPeriod,
            #maxPeriod: maxPeriod,
          },
        ),
        returnValue: _i8.Stream<Duration>.empty(),
      ) as _i8.Stream<Duration>);

  @override
  _i8.Future<Duration?> setUrl(
    String? url, {
    Map<String, String>? headers,
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUrl,
          [url],
          {
            #headers: headers,
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setFilePath(
    String? filePath, {
    Duration? initialPosition,
    bool? preload = true,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFilePath,
          [filePath],
          {
            #initialPosition: initialPosition,
            #preload: preload,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setAsset(
    String? assetPath, {
    String? package,
    bool? preload = true,
    Duration? initialPosition,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAsset,
          [assetPath],
          {
            #package: package,
            #preload: preload,
            #initialPosition: initialPosition,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setAudioSource(
    _i3.AudioSource? audioSource, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSource,
          [audioSource],
          {
            #preload: preload,
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> setAudioSources(
    List<_i3.AudioSource>? audioSources, {
    bool? preload = true,
    int? initialIndex,
    Duration? initialPosition,
    _i3.ShuffleOrder? shuffleOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSources,
          [audioSources],
          {
            #preload: preload,
            #initialIndex: initialIndex,
            #initialPosition: initialPosition,
            #shuffleOrder: shuffleOrder,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<Duration?> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<void> addAudioSource(_i3.AudioSource? audioSource) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAudioSource,
          [audioSource],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> insertAudioSource(
    int? index,
    _i3.AudioSource? audioSource,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAudioSource,
          [
            index,
            audioSource,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addAudioSources(List<_i3.AudioSource>? audioSources) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAudioSources,
          [audioSources],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> insertAudioSources(
    int? index,
    List<_i3.AudioSource>? audioSources,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAudioSources,
          [
            index,
            audioSources,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeAudioSourceAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeAudioSourceAt,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeAudioSourceRange(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAudioSourceRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> moveAudioSource(
    int? currentIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveAudioSource,
          [
            currentIndex,
            newIndex,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAudioSources() => (super.noSuchMethod(
        Invocation.method(
          #clearAudioSources,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Duration?> setClip({
    Duration? start,
    Duration? end,
    dynamic tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setClip,
          [],
          {
            #start: start,
            #end: end,
            #tag: tag,
          },
        ),
        returnValue: _i8.Future<Duration?>.value(),
      ) as _i8.Future<Duration?>);

  @override
  _i8.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSkipSilenceEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setSkipSilenceEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setLoopMode(_i3.LoopMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setLoopMode,
          [mode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setShuffleModeEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setShuffleModeEnabled,
          [enabled],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> shuffle() => (super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAutomaticallyWaitsToMinimizeStalling(
          bool? automaticallyWaitsToMinimizeStalling) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutomaticallyWaitsToMinimizeStalling,
          [automaticallyWaitsToMinimizeStalling],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setCanUseNetworkResourcesForLiveStreamingWhilePaused(
          bool? canUseNetworkResourcesForLiveStreamingWhilePaused) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCanUseNetworkResourcesForLiveStreamingWhilePaused,
          [canUseNetworkResourcesForLiveStreamingWhilePaused],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setPreferredPeakBitRate(double? preferredPeakBitRate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPreferredPeakBitRate,
          [preferredPeakBitRate],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAllowsExternalPlayback(bool? allowsExternalPlayback) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAllowsExternalPlayback,
          [allowsExternalPlayback],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seek(
    Duration? position, {
    int? index,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
          {#index: index},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekToNext() => (super.noSuchMethod(
        Invocation.method(
          #seekToNext,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> seekToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #seekToPrevious,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setAndroidAudioAttributes(
          _i12.AndroidAudioAttributes? audioAttributes) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAndroidAudioAttributes,
          [audioAttributes],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setWebCrossOrigin(_i3.WebCrossOrigin? webCrossOrigin) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWebCrossOrigin,
          [webCrossOrigin],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setWebSinkId(String? webSinkId) => (super.noSuchMethod(
        Invocation.method(
          #setWebSinkId,
          [webSinkId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
